### ISSUE TITLE
Proposed new additions

### ISSUE THREAD

**Issue by blakek** [gsandf/eslint-config-gsandf#5]
I was running through some popular packages and found a few rules I think make sense with the config.

**Proposed rules:**

* `array-callback-return` - Enforces return statements in callbacks of array’s methods
* `no-extra-label` - Disallow unnecessary Labels (catches incorrectly formed objects)
* `no-native-reassign` - Sets many (browser) globals as read-only.  Helps catch confusing errors when using variables with names conflicting with globals, such as `location`
* `no-restricted-syntax` - ['warn', 'WithStatement'] Disallows `with`
* `no-restricted-globals` - Disallow directly using some global variables without accessing through `window`. See [here](https://github.com/facebook/create-react-app/blob/next/packages/confusing-browser-globals/index.js) for the list CRA uses.  Proposed to be implemented with `'no-restricted-globals': ['error'].concat(restrictedGlobals)`
* `no-unused-labels` - Disallow unnecessary Labels (catches incorrectly formed objects)
* `no-useless-concat` - Disallows concatenation of short (e.g. non-multiline) string literals
* `radix` - ensures radix is specified when using `parseInt`.  Proposed using with `as-needed` option.
* `require-yield` - prevents useless generators without yield

**Comment by sunnyzanchi** [comment]
I think [`no-shadow`](https://eslint.org/docs/rules/no-shadow) would be a good one to add as well

**Comment by blakek** [comment]
One more I've been looking for but didn't know the name of:

* [`no-implicit-coercion`](https://eslint.org/docs/rules/no-implicit-coercion) - Disallows common, difficult-to-understand type coercions.  For example, `+num` is disallowed and fixed with something like `Number(num)`.

It's not a rule I think we _need_ (e.g. what it warns isn't likely a mistake like `no-extra-label`), but it does help keep code more readable.  Cost/benefit-wise, it's probably most useful if we assume we're going to maintain and read the code more often than write it.
